### ISSUE TITLE
Ruby version 2.4.1 support

### ISSUE THREAD

**Issue by AledLewis** [nak1114/rbenv-win#7]
Hey, 

Thanks for making this, I've found it pretty useful. Do you know how I'd go about getting 2.4.1 supported? I see there's a download site, do you know who keeps it up to date?

**Comment by nak1114** [comment]
Hi,

The Rbenv-win supports only installable versions of RubyInstaller 1.
Since ruby 2.4.1 requires installation by RubyInstaller 2, it can not be installed with the current this.
I do not know when I will support the new installer with the tool.
I am glad that you will feel free to fork this and PR if you go well.

**Comment by AledLewis** [comment]
Hey,

Thanks for the response. I'll see if I can take a look this week.

**Comment by meustrus** [comment]
Hey, I made a [PR](https://github.com/nak1114/rbenv-win/pull/11) to add these versions. I just dropped the 7z files into the list and everything seems to work ok. The only issue was DevKit, but running `ridk.cmd install` from RubyInstaller2 installs MSys as required and I am able to build gems with native extensions. Please take a look and let me know if there's anything I missed.

**Comment by nak1114** [comment]
Thanks for your PR.
I merged it.
